int exception_test(void);
